language: cpp
os: linux
group: stable
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
  - git clone git@github.com:google/googletest.git
  - cd src
  - make -f MakeTests.mk GTEST_DIR=../googletest/googletest
  - ./NumberTest
  - ./LexicalAnalyzerTest



