Kalulacka: team22::Calc::LexicalAnalyzer Class Reference
team22::Calc::LexicalAnalyzer Class Reference
#include <LexicalAnalyzer.h>
Public Member Functions
void pushSymbol (char symbol)
void registrLexCallback (LexIdentificationObserver *lexCallbackObject)
void processNumberSymbol (char symbol)
bool isNumberSymbol (char symbol) const
void clear ()
void processOperator (char symbol)
Private Types
enum State { Number, Operator, Init }
Private Member Functions
void sendLex (Lex lex)
Lex getCharLex (char c)
Math::Number savedToNumber ()
Private Attributes
State state = Init
std::set< LexIdentificationObserver * > lexCallbackObjects
std::string saved = ""
Detailed Description
Třída sloužící k lexikální analyze vstupů přebírá znaky pomocí fce pushSymbol() a ve chvíli identifikace lexému předá tento interpretu a pokud byl registrovaný volá callback kterému tento lexém předá.
Definition at line 26 of file LexicalAnalyzer.h.
Member Enumeration Documentation
State
enum team22::Calc::LexicalAnalyzer::State private
Enumerator
Number
Operator
Init
Definition at line 28 of file LexicalAnalyzer.h.
Member Function Documentation
clear()
void team22::Calc::LexicalAnalyzer::clear ()
Vyresetuje lexikální analyzátor
Definition at line 167 of file LexicalAnalyzer.cpp.
References Init, saved, and state.
Referenced by processNumberSymbol(), processOperator(), and pushSymbol().
getCharLex()
Lex team22::Calc::LexicalAnalyzer::getCharLex (char c) private
Vrací lexém daného znaku
Parameters
c znak nebo číslice k převodu na lexém
Definition at line 19 of file LexicalAnalyzer.cpp.
References team22::Calc::Lex::ADD, team22::Calc::Lex::CLEAR, team22::Calc::Lex::DIV, team22::Calc::Lex::EVAL, team22::Calc::Lex::EXP, team22::Calc::Lex::FACTORIAL, team22::Calc::Lex::MOD, team22::Calc::Lex::MUL, and team22::Calc::Lex::SUB.
Referenced by pushSymbol().
isNumberSymbol()
bool team22::Calc::LexicalAnalyzer::isNumberSymbol (char symbol) const
Jedná se o symbol tvořící číslo tedy číslice, . nebo i
Parameters
symbol
Returns
Definition at line 138 of file LexicalAnalyzer.cpp.
Referenced by pushSymbol().
processNumberSymbol()
void team22::Calc::LexicalAnalyzer::processNumberSymbol (char symbol)
Zpracuje uložený řetězec saved a vrátí jej jako číslo
Parameters
symbol
Definition at line 148 of file LexicalAnalyzer.cpp.
References clear(), Init, Number, saved, savedToNumber(), sendLex(), and state.
Referenced by pushSymbol().
processOperator()
void team22::Calc::LexicalAnalyzer::processOperator (char symbol)
Zpracuje výceznakový operátor
Parameters
symbol
Definition at line 80 of file LexicalAnalyzer.cpp.
References team22::Calc::Lex::BS, clear(), team22::Calc::Lex::NEG, Operator, team22::Calc::Lex::ROOT, saved, sendLex(), and state.
Referenced by pushSymbol().
pushSymbol()
void team22::Calc::LexicalAnalyzer::pushSymbol (char symbol)
Předá znak k analýze
Parameters
symbol symbol abecedy přijímané lexikálním analyzátorem
Exceptions
LexicalAnalyserException
Definition at line 61 of file LexicalAnalyzer.cpp.
References clear(), getCharLex(), isNumberSymbol(), Number, processNumberSymbol(), processOperator(), savedToNumber(), sendLex(), and state.
Referenced by team22::Calc::Equation::backSpace(), and team22::Calc::Equation::pushSymbol().
registrLexCallback()
void team22::Calc::LexicalAnalyzer::registrLexCallback (LexIdentificationObserver * lexCallbackObject)
Registruje objekt k odběru rozeznaných lexémů vícenásobná registrace stejné instance odběratele neprovede nic
Parameters
lexCallbackObject objekt na němž
Definition at line 143 of file LexicalAnalyzer.cpp.
References lexCallbackObjects.
Referenced by BackendTester::BackendTester(), team22::Calc::Equation::Equation(), and LexicalAnalyzerTestBase::LexicalAnalyzerTestBase().
savedToNumber()
Math::Number team22::Calc::LexicalAnalyzer::savedToNumber () private
Vrací číslo typu double převedené z textového řetězce
Parameters
s textový řetězec pro převod
Definition at line 45 of file LexicalAnalyzer.cpp.
References saved.
Referenced by processNumberSymbol(), and pushSymbol().
sendLex()
void team22::Calc::LexicalAnalyzer::sendLex (Lex lex) private
Předá lexém všem registrovaným objektům
Parameters
lex lexém k předání
Definition at line 13 of file LexicalAnalyzer.cpp.
References lexCallbackObjects.
Referenced by processNumberSymbol(), processOperator(), and pushSymbol().
Member Data Documentation
lexCallbackObjects
std::set<LexIdentificationObserver *> team22::Calc::LexicalAnalyzer::lexCallbackObjects private
Množina Objektů na nichž bude volán callback při rozeznání lexemů
Definition at line 39 of file LexicalAnalyzer.h.
Referenced by registrLexCallback(), and sendLex().
saved
std::string team22::Calc::LexicalAnalyzer::saved = "" private
Řetězec, který obsahuje znaky, které ještě nebyly rozeznány jako lexém
Definition at line 44 of file LexicalAnalyzer.h.
Referenced by clear(), processNumberSymbol(), processOperator(), and savedToNumber().
state
State team22::Calc::LexicalAnalyzer::state = Init private
Definition at line 34 of file LexicalAnalyzer.h.
Referenced by clear(), processNumberSymbol(), processOperator(), and pushSymbol().
The documentation for this class was generated from the following files:
LexicalAnalyzer.h
LexicalAnalyzer.cpp