Kalulacka: team22::Calc::Lex Class Reference
team22::Calc::Lex Class Reference
Reprezentace lexému kalkulačky tedy čísla nebo operace.
#include <Lex.h>
Classes
union Value
reprezentace hodnoty lexému
Public Types
enum Types { OPERATOR, NUMBER }
Typy lexémů
enum Operator {
ADD, SUB, DIV, MUL,
EXP, ROOT, FACTORIAL, MOD,
NEG, EVAL, CLEAR, BS
}
Jednotlivé operace.
Public Member Functions
Lex (Operator oper)
Konstrukce lexému typu operátor.
Lex (Math::Number number)
Konstrukce lexému typu číslo.
const Value & getValue () const
vrací hodnotu lexému
Types getType () const
vrací typ lexému
bool isNumber () const
Testuje zda je lexém číslo.
bool isOperator () const
Testuje zda je lexém operátor.
Math::Number getAsNumber () const
Operator getAsOperator () const
bool operator== (const Lex &rhs) const
bool operator!= (const Lex &rhs) const
Public Attributes
const char * OperatorNames [12]
ADD,.
Protected Attributes
Value value
Types type
Friends
std::ostream & operator<< (std::ostream &os, const Lex &lex)
std::stringstream & operator<< (std::stringstream &os, const Lex &lex)
Detailed Description
Reprezentace lexému kalkulačky tedy čísla nebo operace.
Definition at line 18 of file Lex.h.
Member Enumeration Documentation
Operator
enum team22::Calc::Lex::Operator
Jednotlivé operace.
Enumerator
ADD
SUB
DIV
MUL
EXP
ROOT
FACTORIAL
MOD
NEG
EVAL
CLEAR
BS
Definition at line 33 of file Lex.h.
Types
enum team22::Calc::Lex::Types
Typy lexémů
Enumerator
OPERATOR
NUMBER
Definition at line 24 of file Lex.h.
Constructor & Destructor Documentation
Lex() [1/2]
team22::Calc::Lex::Lex (Operator oper)
Konstrukce lexému typu operátor.
Parameters
oper
Definition at line 30 of file Lex.cpp.
References NUMBER, team22::Calc::Lex::Value::number, team22::Calc::Lex::Value::oper, type, and value.
Lex() [2/2]
team22::Calc::Lex::Lex (Math::Number number)
Konstrukce lexému typu číslo.
Parameters
number
Member Function Documentation
getAsNumber()
team22::Math::Number team22::Calc::Lex::getAsNumber () const
Exceptions
LexException tento lexém pokud není číslo
Returns
number
Definition at line 42 of file Lex.cpp.
References isNumber(), team22::Calc::Lex::Value::number, and value.
Referenced by operator!=(), and operator==().
getAsOperator()
team22::Calc::Lex::Operator team22::Calc::Lex::getAsOperator () const
Exceptions
LexException tento lexém pokud není Operator
Returns
operator
Definition at line 50 of file Lex.cpp.
References isOperator(), team22::Calc::Lex::Value::oper, and value.
Referenced by operator!=(), operator==(), and team22::Calc::Equation::sendIdentifiedLex().
getType()
team22::Calc::Lex::Types team22::Calc::Lex::getType () const
vrací typ lexému
Returns
type
Definition at line 15 of file Lex.cpp.
References type.
getValue()
const team22::Calc::Lex::Value & team22::Calc::Lex::getValue () const
vrací hodnotu lexému
Definition at line 10 of file Lex.cpp.
References value.
isNumber()
bool team22::Calc::Lex::isNumber () const
Testuje zda je lexém číslo.
Returns
true pokud je číslo
Definition at line 20 of file Lex.cpp.
References type.
Referenced by getAsNumber(), operator!=(), and operator==().
isOperator()
bool team22::Calc::Lex::isOperator () const
Testuje zda je lexém operátor.
Returns
true pokud je operátor
Definition at line 25 of file Lex.cpp.
References type.
Referenced by getAsOperator(), operator==(), and team22::Calc::Equation::sendIdentifiedLex().
operator!=()
bool team22::Calc::Lex::operator!= (const Lex & rhs) const
Definition at line 69 of file Lex.cpp.
References getAsNumber(), getAsOperator(), isNumber(), and OperatorNames.
operator==()
bool team22::Calc::Lex::operator== (const Lex & rhs) const
Definition at line 59 of file Lex.cpp.
References getAsNumber(), getAsOperator(), isNumber(), isOperator(), and type.
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & os, const Lex & lex) friend
operator<< [2/2]
std::stringstream& operator<< (std::stringstream & os, const Lex & lex) friend
Member Data Documentation
OperatorNames
const char* team22::Calc::Lex::OperatorNames[12]
Initial value:
{
        "+",
        "-",
        "/",
        "*",
        "^",
        "√",
        "!",
        "%",
        "*-1",
        "=",
        "CLEAR",
        "BS",
    }
ADD,.
SUB, DIV, MUL, EXP, ROOT, FACTORIAL, MOD, NEG, EVAL, CLEAR, BS
Definition at line 49 of file Lex.h.
Referenced by operator!=().
type
Types team22::Calc::Lex::type protected
Definition at line 75 of file Lex.h.
Referenced by getType(), isNumber(), isOperator(), Lex(), and operator==().
value
Value team22::Calc::Lex::value protected
Definition at line 74 of file Lex.h.
Referenced by getAsNumber(), getAsOperator(), getValue(), and Lex().
The documentation for this class was generated from the following files:
Lex.h
Lex.cpp