Kalulacka: BackendTester Class Reference
BackendTester Class Reference
Public Member Functions
BackendTester ()
void onEquationChange () override
void onError (InterpretException exception) override
void onResultChange (team22::Math::Number result) override
virtual ~BackendTester ()
Public Attributes
Interpret interpret
LexicalAnalyzer lexicalAnalyzer
Equation equation
stringstream strEquation
InterpretException * error = nullptr
Number result = {0}
Additional Inherited Members
Detailed Description
Definition at line 21 of file backendTest.cpp.
Constructor & Destructor Documentation
BackendTester()
BackendTester::BackendTester () inline
Definition at line 31 of file backendTest.cpp.
References team22::Calc::Equation::registrEquationObserver(), team22::Calc::LexicalAnalyzer::registrLexCallback(), and team22::Calc::Interpret::registrResultCallback().
~BackendTester()
virtual BackendTester::~BackendTester () inline virtual
Definition at line 55 of file backendTest.cpp.
Member Function Documentation
onEquationChange()
void BackendTester::onEquationChange () inline override virtual
Implements team22::Calc::EquationObserver.
Definition at line 39 of file backendTest.cpp.
onError()
void BackendTester::onError (InterpretException exception) inline override virtual
Callback volaný pokud vznikla chyba při výpočtu
Parameters
InterpretException
Implements team22::Calc::ResultObserver.
Definition at line 45 of file backendTest.cpp.
onResultChange()
void BackendTester::onResultChange (team22::Math::Number result) inline override virtual
Callback volaný při změně výsledku
Parameters
result
Implements team22::Calc::ResultObserver.
Definition at line 50 of file backendTest.cpp.
Member Data Documentation
equation
Equation BackendTester::equation
Definition at line 26 of file backendTest.cpp.
Referenced by TEST().
error
InterpretException* BackendTester::error = nullptr
Definition at line 28 of file backendTest.cpp.
Referenced by TEST().
interpret
Interpret BackendTester::interpret
Definition at line 24 of file backendTest.cpp.
lexicalAnalyzer
LexicalAnalyzer BackendTester::lexicalAnalyzer
Definition at line 25 of file backendTest.cpp.
result
Number BackendTester::result = {0}
Definition at line 29 of file backendTest.cpp.
Referenced by TEST().
strEquation
stringstream BackendTester::strEquation
Definition at line 27 of file backendTest.cpp.
Referenced by TEST().
The documentation for this class was generated from the following file:
tests/backendTest.cpp