Kalulacka: team22::Math::Number Class Reference
team22::Math::Number Class Reference
#include <Number.h>
Public Member Functions
double getReal () const
double getImaginary () const
Number (double real, double imaginary=0)
Konstruktor.
Number (const std::complex< double > &other)
Konstruktor.
Number add (Number addend) const
Sčítání
Number operator+ (const Number &number) const
Number sub (Number subtrahend) const
Odečítání
Number operator- (const Number &number) const
Number mul (Number multiplier) const
Násobení
Number operator* (const Number &number) const
Number div (Number divisor) const
Dělení
Number operator/ (const Number &number) const
Number pow (Number exponent) const
Umocňování
Number operator^ (const Number &number) const
Number root (Number degree) const
Odmocňování
Number mod (Number divisor) const
Zbytek po dělení
Number operator% (const Number &number) const
Number fact ()
Faktoriál.
Number operator! ()
bool operator== (const Number &rhs) const
bool operator!= (const Number &rhs) const
Private Member Functions
operator std::complex< double > () const
std::complex< double > gamma (std::complex< double > z)
bool anyParamNan (double param1, double param2, double param3, double param4) const
bool anyParamInf (double param1, double param2, double param3, double param4) const
bool allParamsInf (double param1, double param2, double param3, double param4) const
Private Attributes
std::complex< double > value
Friends
std::ostream & operator<< (std::ostream &os, const Number &number)
Detailed Description
Třída reprezentující číslo v komplexní rovině a operace nad tímto číslem
Definition at line 24 of file Number.h.
Constructor & Destructor Documentation
Number() [1/2]
Number::Number (double real, double imaginary = 0)
Konstruktor.
Parameters
real Reálná část
imaginary Imaginární část
Definition at line 42 of file Number.cpp.
Referenced by operator std::complex< double >().
Number() [2/2]
Number::Number (const std::complex< double > & other)
Konstruktor.
Parameters
other Komplexní číslo
Definition at line 46 of file Number.cpp.
Member Function Documentation
add()
Number Number::add (Number addend) const
Sčítání
Parameters
addend sčítanec
Returns
součet
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo pokud jsou obě části operandů nekonečno a zároveň operandy nejsou ze stejných kvadrantů komplexní roviny
Definition at line 50 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
allParamsInf()
bool Number::allParamsInf (double param1, double param2, double param3, double param4) const private
Returns
True pokud jsou všechny parametry nekonečno, jiank False
Definition at line 28 of file Number.cpp.
Referenced by operator std::complex< double >().
anyParamInf()
bool Number::anyParamInf (double param1, double param2, double param3, double param4) const private
Returns
True pokud je některý z parametrů nekonečno, jiank False
Definition at line 22 of file Number.cpp.
Referenced by operator std::complex< double >().
anyParamNan()
bool Number::anyParamNan (double param1, double param2, double param3, double param4) const private
Returns
True pokud je některý z parametrů Nan, jiank False
Definition at line 16 of file Number.cpp.
Referenced by operator std::complex< double >().
div()
Number Number::div (Number divisor) const
Dělení
Parameters
divisor dělitel
Returns
rozdíl
Exceptions
UndefinedException Pokud je některá část operandů nan nebo obě části obou operandů jsou nekonečno nebo je dělitel nulový a obě části dělence nejsou nekonečno a reálná část dělence není pozitivní nekonečno a imaginární část dělence není nekonečno
Definition at line 96 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
fact()
Number Number::fact ()
Faktoriál.
Returns
faktoriál
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo jsou obě části operandů nekonečno nebo je reálná část operandu záporné nekonečno
Definition at line 181 of file Number.cpp.
Referenced by operator std::complex< double >().
gamma()
complex< double > Number::gamma (std::complex< double > z) private
Gamma funkce implementovaná pomocí Lanczosovy aproximace
Parameters
z vstupní operand
Returns
gamma čísla z
Definition at line 224 of file Number.cpp.
References c, getImaginary(), and getReal().
Referenced by operator std::complex< double >().
getImaginary()
double Number::getImaginary () const
Imaginární část
Returns
Definition at line 38 of file Number.cpp.
Referenced by add(), div(), gamma(), mod(), mul(), operator std::complex< double >(), pow(), root(), and sub().
getReal()
double Number::getReal () const
Realná část
Returns
Definition at line 34 of file Number.cpp.
Referenced by add(), div(), gamma(), mod(), mul(), operator std::complex< double >(), pow(), root(), and sub().
mod()
Number Number::mod (Number divisor) const
Zbytek po dělení
Parameters
divisor dělitel
Returns
zbytek
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo nekonečno nebo pokud je dělitel nulový
Definition at line 160 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
mul()
Number Number::mul (Number multiplier) const
Násobení
Parameters
multiplier činitel
Returns
součin
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo nekonečno
Definition at line 82 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
operator std::complex< double >()
team22::Math::Number::operator std::complex< double > () const inline explicit private
Definition at line 30 of file Number.h.
References add(), allParamsInf(), anyParamInf(), anyParamNan(), div(), fact(), gamma(), getImaginary(), getReal(), mod(), mul(), Number(), operator!(), operator!=(), operator%(), operator*(), operator+(), operator-(), operator/(), operator<<, operator==(), operator^(), pow(), root(), sub(), and value.
operator!()
Number Number::operator! ()
See also
::fact
Definition at line 204 of file Number.cpp.
Referenced by operator std::complex< double >().
operator!=()
bool team22::Math::Number::operator!= (const Number & rhs) const
Definition at line 263 of file Number.cpp.
Referenced by operator std::complex< double >().
operator%()
Number Number::operator% (const Number & number) const
See also
::mod
Definition at line 177 of file Number.cpp.
Referenced by operator std::complex< double >().
operator*()
Number Number::operator* (const Number & number) const
See also
::mul
Definition at line 92 of file Number.cpp.
Referenced by operator std::complex< double >().
operator+()
Number Number::operator+ (const Number & number) const
See also
::add
Definition at line 62 of file Number.cpp.
Referenced by operator std::complex< double >().
operator-()
Number Number::operator- (const Number & number) const
See also
::sub
Definition at line 78 of file Number.cpp.
Referenced by operator std::complex< double >().
operator/()
Number Number::operator/ (const Number & number) const
See also
::div
Definition at line 113 of file Number.cpp.
Referenced by operator std::complex< double >().
operator==()
bool team22::Math::Number::operator== (const Number & rhs) const
Definition at line 258 of file Number.cpp.
References value.
Referenced by operator std::complex< double >().
operator^()
Number Number::operator^ (const Number & number) const
See also
::pow
Definition at line 137 of file Number.cpp.
Referenced by operator std::complex< double >().
pow()
Number Number::pow (Number exponent) const
Umocňování
Parameters
exponent mocnitel
Returns
mocnina
Exceptions
UndefinedException TODO
Definition at line 117 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
root()
Number Number::root (Number degree) const
Odmocňování
Parameters
degree odmocnitel
Returns
odmocnina
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo nekonečno nebo pokud je některá z částí odmocněnce nenulová a odmocnitel je nulový
Definition at line 141 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
sub()
Number Number::sub (Number subtrahend) const
Odečítání
Parameters
subtrahend menšitel
Returns
rozdíl
Exceptions
UndefinedException pokud je některá z částí operandů nan nebo pokud jsou obě části operandů nekonečno a zároveň operandy nejsou z opačných kvadrantů komplexní roviny
Definition at line 66 of file Number.cpp.
References getImaginary(), and getReal().
Referenced by operator std::complex< double >().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Number & number) friend
Vypíše komplexní číslo ve tvaru: reálná_část +/- imaginární_část. Pokud je některá z částí 0, není vypsána, pokud jsou 0 části obě, vypíše 0.
Referenced by operator std::complex< double >().
Member Data Documentation
value
std::complex<double> team22::Math::Number::value private
Definition at line 28 of file Number.h.
Referenced by operator std::complex< double >(), and operator==().
The documentation for this class was generated from the following files:
math/Number.h
math/Number.cpp