#all (přeloží projekt - včetně programu pro profiling)
#pack (zabalí projekt tak, aby mohl být odevzdán)
#clean (smaže všechny soubory, co nemají být odevzdány)
#test (spustí testy matematické knihovny)
test:
	make -f MakeTests NumberTest;./NumberTest
clean:
	rm -f NumberTest *.o *.a
#doc (spustí generování dokumentace)
#run (spustí program)
