#all (přeloží projekt - včetně programu pro profiling)
#pack (zabalí projekt tak, aby mohl být odevzdán)
#clean (smaže všechny soubory, co nemají být odevzdány)
#test (spustí testy matematické knihovny)
test:
	make -f MakeTests.mk InterpretTest;./InterpretTest
clean:
	rm -f InterpretTest *.o *.a tests/*.o
#doc (spustí generování dokumentace)
#run (spustí program)
