Kalulacka: team22::Calc::Interpret Class Reference
team22::Calc::Interpret Class Reference
#include <Interpret.h>
Public Member Functions
void registrResultCallback (ResultObserver *resultCallbackObject)
void sendIdentifiedLex (Lex lex) override
Public Attributes
std::set< ResultObserver * > resultCallbackObjects
Private Member Functions
void notifyResultChanged ()
void notifyAboutError (InterpretException exception)
Detailed Description
Definition at line 48 of file Interpret.h.
Member Function Documentation
notifyAboutError()
void Interpret::notifyAboutError (InterpretException exception) private
Předá informaci o změně výsledků pozorovatelům
Examples:
/root/Documents/GitClone/FIT_IVS_PROJECT2/src/Interpret.h.
Definition at line 28 of file Interpret.cpp.
References resultCallbackObjects.
notifyResultChanged()
void Interpret::notifyResultChanged () private
Předá informaci o změně výsledků pozorovatelům
Examples:
/root/Documents/GitClone/FIT_IVS_PROJECT2/src/Interpret.h.
Definition at line 22 of file Interpret.cpp.
References resultCallbackObjects.
registrResultCallback()
void Interpret::registrResultCallback (ResultObserver * resultCallbackObject)
Registruje objekt k odběru rozeznaných lexémů vícenásobná registrace stejné instance odběratele neprovede nic
Parameters
resultCallbackObject objekt na němž bude volán callback při změně výsledku nebo chybě
Examples:
/root/Documents/GitClone/FIT_IVS_PROJECT2/src/Interpret.h.
Definition at line 17 of file Interpret.cpp.
References resultCallbackObjects.
Referenced by BackendTester::BackendTester(), and InterpretTest::InterpretTest().
sendIdentifiedLex()
void Interpret::sendIdentifiedLex (Lex lex) override virtual
Příjme lexém k interpretaci
See also
Interpret popis postupu interpretace
Parameters
lex
Implements team22::Calc::LexIdentificationObserver.
Examples:
/root/Documents/GitClone/FIT_IVS_PROJECT2/src/Interpret.h.
Definition at line 12 of file Interpret.cpp.
Referenced by team22::Calc::Equation::reComputeResult(), and team22::Calc::Equation::sendIdentifiedLex().
Member Data Documentation
resultCallbackObjects
std::set<ResultObserver *> team22::Calc::Interpret::resultCallbackObjects
Množina Objektů na nichž bude volán callback při změně výsledku nebo chybě
Examples:
/root/Documents/GitClone/FIT_IVS_PROJECT2/src/Interpret.h.
Definition at line 64 of file Interpret.h.
Referenced by notifyAboutError(), notifyResultChanged(), and registrResultCallback().
The documentation for this class was generated from the following files:
src/Interpret.h
src/Interpret.cpp