Kalulacka: team22::Calc::Equation Class Reference
team22::Calc::Equation Class Reference
Třída reprezentující rovnici.
#include <Equation.h>
Public Member Functions
Equation (LexicalAnalyzer &lexicalAnalyzer, Interpret &interpret)
void pushSymbol (char symbol)
void sendIdentifiedLex (Lex lex) override
void onResultChange (Math::Number result) override
void onError (InterpretException exception) override
void backSpace ()
Provede operaci backspace Pokud je rovnice zakončena číslem odstraní poslední číslici jinak poslední lexem (operator) přepočítá rovnici.
void registrEquationObserver (EquationObserver *equationObservers)
Private Member Functions
void reComputeResult ()
void notifyEquationObserver ()
bool isNumberSymbol (char &symbol)
void pushLex (Lex *lex)
Private Attributes
std::string numberBuffer
std::vector< Lex * > data
LexicalAnalyzer lexicalAnalyzer
Interpret interpret
std::set< EquationObserver * > equationObservers
Math::Number lastResult = {0}
Friends
std::stringstream & operator<< (std::stringstream &os, const Equation &equation)
std::ostream & operator<< (std::ostream &os, const Equation &equation)
Detailed Description
Třída reprezentující rovnici.
Třída přebírá znaky a předává je Lexikálnímu analyzátoru, dále pozoruje Identifikaci Lexému. Při každé změně rovnice třída upozorní své pozorovatele o této změně. Pokud příjme lexem Lex::BS odebere číslici(i beru jako číslici) či operátor z konce rovnice a rovnici přepočítá Pokud příjme lexem Lex::CLEAR rovnice se smaže, Operátory Lex::BS Lex::CLEAR a Lex::EVAL se do rovnice nezapisují. Po Lex::EVAL pokud následuje číslo rovnice začíná tímto číslem a jinak začíná výsledkem předchozí rovnice pokud taková není 0.
Definition at line 30 of file Equation.h.
Constructor & Destructor Documentation
Equation()
Equation::Equation (LexicalAnalyzer & lexicalAnalyzer, Interpret & interpret)
Parameters
lexicalAnalyzer
interpret
Definition at line 106 of file Equation.cpp.
References team22::Calc::LexicalAnalyzer::registrLexCallback().
Member Function Documentation
backSpace()
void Equation::backSpace ()
Provede operaci backspace Pokud je rovnice zakončena číslem odstraní poslední číslici jinak poslední lexem (operator) přepočítá rovnici.
Definition at line 56 of file Equation.cpp.
References data, lexicalAnalyzer, numberBuffer, team22::Calc::LexicalAnalyzer::pushSymbol(), and reComputeResult().
Referenced by sendIdentifiedLex().
isNumberSymbol()
bool Equation::isNumberSymbol (char & symbol) private
Jedná se o znak čísla tedy číslici nebo i
Definition at line 95 of file Equation.cpp.
Referenced by pushSymbol().
notifyEquationObserver()
void Equation::notifyEquationObserver () private
upozorní odebíratele na změnu rovnice
Definition at line 89 of file Equation.cpp.
References equationObservers.
Referenced by pushSymbol(), and sendIdentifiedLex().
onError()
void Equation::onError (InterpretException exception) override virtual
Parameters
exception
Implements team22::Calc::ResultObserver.
Definition at line 122 of file Equation.cpp.
References data, and numberBuffer.
onResultChange()
void Equation::onResultChange (Math::Number result) override virtual
Parameters
result
Implements team22::Calc::ResultObserver.
Definition at line 117 of file Equation.cpp.
References lastResult.
pushLex()
void Equation::pushLex (Lex * lex) private
zpracuje příchozí Lexém
Parameters
lex
Definition at line 112 of file Equation.cpp.
References data.
Referenced by sendIdentifiedLex().
pushSymbol()
void Equation::pushSymbol (char symbol)
Předání symbolu rovnici
Exceptions
LexicalAnalyzerException
Definition at line 45 of file Equation.cpp.
References isNumberSymbol(), lexicalAnalyzer, notifyEquationObserver(), numberBuffer, and team22::Calc::LexicalAnalyzer::pushSymbol().
Referenced by TEST().
reComputeResult()
void Equation::reComputeResult () private
přepočítá výsledek
Definition at line 100 of file Equation.cpp.
References data, interpret, and team22::Calc::Interpret::sendIdentifiedLex().
Referenced by backSpace().
registrEquationObserver()
void Equation::registrEquationObserver (EquationObserver * equationObservers)
Zaregistruje pozorovatele změny rovnice
Parameters
equationObservers
Definition at line 84 of file Equation.cpp.
References equationObservers.
Referenced by BackendTester::BackendTester().
sendIdentifiedLex()
void Equation::sendIdentifiedLex (Lex lex) override virtual
Parameters
lex
Implements team22::Calc::LexIdentificationObserver.
Definition at line 15 of file Equation.cpp.
References backSpace(), team22::Calc::Lex::BS, team22::Calc::Lex::CLEAR, data, team22::Calc::Lex::EVAL, team22::Calc::Lex::getAsOperator(), interpret, team22::Calc::Lex::isOperator(), lastResult, notifyEquationObserver(), numberBuffer, pushLex(), and team22::Calc::Interpret::sendIdentifiedLex().
Friends And Related Function Documentation
operator<< [1/2]
std::stringstream& operator<< (std::stringstream & os, const Equation & equation) friend
operator<< [2/2]
std::ostream& operator<< (std::ostream & os, const Equation & equation) friend
Member Data Documentation
data
std::vector<Lex *> team22::Calc::Equation::data private
Lexémy tvořící rovnici
Definition at line 42 of file Equation.h.
Referenced by backSpace(), onError(), pushLex(), reComputeResult(), and sendIdentifiedLex().
equationObservers
std::set<EquationObserver *> team22::Calc::Equation::equationObservers private
Pozorovatele
Definition at line 59 of file Equation.h.
Referenced by notifyEquationObserver(), and registrEquationObserver().
interpret
Interpret team22::Calc::Equation::interpret private
Interpret
Definition at line 54 of file Equation.h.
Referenced by reComputeResult(), and sendIdentifiedLex().
lastResult
Math::Number team22::Calc::Equation::lastResult = {0} private
Poslední výsledek rovnice
Definition at line 64 of file Equation.h.
Referenced by onResultChange(), and sendIdentifiedLex().
lexicalAnalyzer
LexicalAnalyzer team22::Calc::Equation::lexicalAnalyzer private
Lexikální analyzátor
Definition at line 49 of file Equation.h.
Referenced by backSpace(), and pushSymbol().
numberBuffer
std::string team22::Calc::Equation::numberBuffer private
Buffer pro rozepsané číslo číslo v rovnici chceme zobrazovat ješte předním, než je celé identifikováno jako lexem k tomu nám pomáhá tento buffer.
Definition at line 37 of file Equation.h.
Referenced by backSpace(), onError(), pushSymbol(), and sendIdentifiedLex().
The documentation for this class was generated from the following files:
src/Equation.h
src/Equation.cpp